version: "3"

# This docker-compose is for testing the installation process.
# In starts the installation and executes also build of get-started example.
services:
  idf-setup-test:
    image: mcr.microsoft.com/windows/servercore:1809
    command: powershell -c "C:/Scripts/Prepare-Cache.ps1 -IdfVersion ${IDF_VERSION}; C:/Scripts/Install-Idf.ps1 -Installer 'c:/Output/esp-idf-tools-setup-unsigned.exe' -IdfVersion ${IDF_VERSION}; C:/Scripts/Test-Idf.ps1; powershell ;exit $$LASTEXITCODE"
    tmpfs:
      - C:\Users\ContainerAdministrator\.espressif
    volumes:
      - type: bind
        source: C:\projects\esp-idf\tools\windows\tool_setup\Output
        target: C:\Output
        read_only: true
      - type: bind
        source: C:\projects\esp-idf\tools\windows\tool_setup\Scripts
        target: C:\Scripts
        read_only: true
      # releases volume to speed up installation and avoid downloading of files
      - type: bind
        source: C:\projects\esp-tests\installer-docker-runner\.espressif\
        target: C:\Cache
        read_only: true
